<?php
// $Id$

/** * @file
 *
 *  A module for making query to and getting results from a remote Delving Platform Search API.
 *
 */

/**
 * Implements hook_menu()
 */
function delvingsearch_menu() {
  $items[variable_get('delving_search_page_path', DELVING_SEARCH_PAGE_PATH)] = array(
    'title' => 'DELVING Search',
    'description' => 'Page for searching remote Delving Framework API without dependency on the Search module.',
    'page callback' => 'delvingsearch_load_page',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_block_info()
 */
function delvingsearch_block_info() {
  $blocks = array();

  // The array key defines the $delta parameter used in all other block hooks
  $blocks['facets'] = array(
    // The name of the block on the blocks administration page
    'info' => t('Facets block for the Delving Remote Search result page'),
    'status' => 0,
    'visibility' => 1,
    'pages' => variable_get('delving_search_page_path', DELVING_SEARCH_PAGE_PATH),
  );

  return $blocks;
}

/**
 * Implement hook_block_view()
 *
 * @param $delta
 *  The name of the requested block
 */
function delvingsearch_block_view($delta = '') {

  $facets_ar = delvingsearch_facets();

  //  Create an empty block
  $block = array(
    'subject' => '',
    'content' => '',
  );

  if (delving_has_searched() == TRUE && count($facets_ar) > 0) {

    //  Check which block is being requested
    if ($delta == 'facets') {
      // Set the block title
      $block['subject'] = t('Refine your search');

      //  Check if the user can access content
      if (user_access('access content')) {

        // Get the facets array
        $facets_ar = delvingsearch_facets();

        $qps = delvingapi_get_query_params();
        $terms = $qps['query'];

        $content = '';
        // Get the facets from the $facets_ar['facets'] array
        foreach ($facets_ar['facets'] as $facet) {
          // Only display if the facet has any links
          if ($facet->link && $facet['name'] != 'HASDIGITALOBJECT') {
            $content .= '<div class="delving-facets-container">';
            $content .= '<h4>' . $facet['name'] . '</h4>';
            $content .= '<div class="delving-facets">';
            foreach ($facet->link as $link) {

              $facet_link = $link['url'];

              $furl = url(variable_get('delving_search_page_path', DELVING_SEARCH_PAGE_PATH)) . '?query=' . $terms . $facet_link;

              if (!empty($facet_link)) {
                if ($link['isSelected'] != 'true') {
                  $content .= '<a href="' . $furl . '">' . trim($link) . '</a><br/>';
                }
                else {
                  $content .= '<strong><a href="' . $furl . '">' . trim($link) . '</a></strong><br/>';
                }
              }
              // Checkboxes for later
              // Todo onclick functionality for checkbox to launch search (js)
              /*
              if (!empty($facet_link)) {
                  if($link['isSelected']!='true'){
                      $content .= '<input type="checkbox" class="delving-facets-checkbox" value="' . $furl . '"/>';
                  }
                  else {
                     $content .= '<input type="checkbox" class="delving-facets-checkbox" checked="checked" value="' . $furl . '"/>';
                  }
                  $content .= '<a href="?' . $furl . '">' . trim($link) .'</a><br/>';
              }
              */

            }
            $content .= '</div></div>';
          }
        }
        $block['subject'] = t('Refine your search');
        $block['content'] = $content;
      }
    }

  }
  return $block;
}

/**
 * The hook_menu() page callback
 *
 * Displays the page and calls necessary functions needed to run the page functionality
 */
function delvingsearch_load_page() {

//
//  global $theme;
//  // Populate all block regions.
//  $regions = system_region_list($theme);
//  debug($regions);

  drupal_add_css(drupal_get_path('module', 'delvingsearch') . '/delving.css');
  return drupal_get_form('delvingsearch_form');
}

/**
 * Implement hook_form()
 */
function delvingsearch_form($form, &$form_state) {
  // grab query parameters if there are any
  $qps = delvingapi_get_query_params();
  $html = '';
  // there is a query in the URL, do a search and fill up $html
  if (!empty($qps['query'])) {

    $results = delvingapi_remote_search($qps['query'], $qps);
    //$results_ar = array();
    //$results_ar =  delving_set_results($results);
    // Cache response and set semaphore for use by blocks.
    //delving_static_response_cache($results);
    //delving_has_searched(TRUE);
    $html .= $results;
  }

  $form['query'] = array(
    '#type' => 'textfield',
    '#title' => t('Enter a search term'),
    '#size' => 60,
    '#maxlength' => 256,
    '#required' => TRUE,
  );
  $form['submit_query'] = array(
    '#type' => 'submit',
    '#value' => t('Find'),
  );
  $form['#suffix'] = $html;

  return $form;
}

function delvingsearch_form_submit($form, &$form_state) {
  // A simulated 'GET', a bit dirty but it does the job nicely
  // This way when a query is resubmitted using the pager or facet refinement, the same process is followed each time
  global $base_url;
  $redirect_url = $base_url . '/' . variable_get('delving_search_page_path', DELVING_SEARCH_PAGE_PATH);
  $redirect_url .= '?query=' . $form_state['values']['query'];
  $form_state['redirect'] = $redirect_url;
}


/**
 * Outputs html to display the returned results
 *
 * @param  $xml
 * @param  $query
 * @return void
 */
function delvingsearch_show_results($xml, $query) {

  $data = simplexml_load_string($xml);
  $total_records = $data->query['numFound'];
  $num_per_page = variable_get('delving_search_results_rows', DELVING_SEARCH_RESULTS_ROWS);

  // initialize the pager.
  pager_default_initialize($data->query['numFound'], $num_per_page);
  // set up the variables to pass along to the pager
  $variables = array(
    'parameters' => array(
      'query' => $query,
      'rows' => $num_per_page,
//      'quantity' => 6,
    ),
  );

  $output = '<div id="delving">';
  $output .= '<h2>You searched for: ' . $query . '</h2>';
  $output .= '<h3>Number of records found: ' . $total_records . '</h3>';
  $output .= delvingsearch_breadcrumbs();
  if ($data->query['numFound'] > 0) {

    // The pager
    $output .= theme('pager', $variables);
    // The results table
    $output .= "<table class='search-results'>";
    $counter = 0;

    foreach ($data->items->item as $item) {

      // set for namespaces
      $ns_dc = $item->children('http://purl.org/dc/elements/1.1/');
      $ns_dcterms = $item->children('http://purl.org/dc/terms/');
      $ns_abm = $item->children('http://to_be_decided/abm/');
      $ns_eu = $item->children('http://www.europeana.eu/schemas/ese/');

      // dc
      $dc_title = $ns_dc->title;
      $dc_creator = $ns_dc->creator;
      $dc_description = $ns_dc->description;
      $dc_subject = $ns_dc->subject;

      // dcterms
      $dcterms_created = $ns_dcterms->created;
      $dcterms_temporal = $ns_dcterms->termporal;
      $dcterms_rights_holder = $ns_dcterms->rightsHolder;

      // abm
      $abm_county = $ns_abm->county;
      $abm_municipality = $ns_abm->municipality;
      $abm_named_place = $ns_abm->namedPlace;
      $abm_about_person = $ns_abm->aboutPerson;

      // europeana
      $eu_country = $ns_eu->country;
      $eu_object = $ns_eu->object;
      $eu_data_provider = $ns_eu->dataProvider;
      $eu_is_shown_by = $ns_eu->isShownBy;

      $fields_arr = array(
        "Title" => $dc_title,
        "Creator" => $dc_creator,
        "Description" => $dc_description,
        "Subject(s)" => $dc_subject,
        "County" => $abm_county,
        "Municipality" => $abm_municipality,
        "Place" => $abm_named_place,
        "Person(s)" => $abm_about_person
      );

      $output .= '<tr><td width="60px">';

      if (!empty($eu_object)) {
        $output .= '<img width="100px" class="overlay" src="' . $eu_object . '"/>';
      }

      $output .= '</td><td>';
      $output .= delvingsearch_show_fields($fields_arr);
      $output .= '</td></tr>';

      $counter++;
    }

    $output .= '</table>';
    $output .= theme('pager', $variables);


  }
  else {
    $output .= "No results found. Please try another search";
  }

  $output .= '</div>';

  return $output;
}


/**
 * Takes an array and outputs rows of 'key: value' data.
 * If multiple values, then outputs as comma separated.
 *
 * @param  $arr_fields
 * @return string
 */

function delvingsearch_show_fields($arr_fields) {
  $out = "";
  foreach ($arr_fields as $key => $value) {
    // Only one value to show
    if (count($value) == 1) {
      $out .= '<strong>' . $key . ': </strong>' . $value . '<br/>';
    }
      // Multiple values to show
    elseif (count($value) > 1) {
      $counter = 1;
      $size = count($value);
      $out .= '<strong>' . $key . ': </strong>';
      foreach ($value as $key => $val) {
        $out .= $val;
        if ($counter != $size) {
          $out .= ', ';
        }
        $counter++;
      }
      $out .= '<br/>';
    }
  }
  return $out;
}

/**
 * Parses data to return an array of values to be displayed using theme() functions
 *
 * @param  $data
 * @param  $query
 * @return $results
 */
function delvingsearch_set_results($data) {

  $xml = $data;

  if (!is_object($data)) {
    $xml = new SimpleXMLElement($data);
  }

  $results = array();
  $results['total'] = $xml->query['numFound'];
  $results['query'] = $xml->query->terms;
  $results['breadcrumbs'] = $xml->xpath('/results/query/breadCrumbs/breadcrumb');
  $results['facets'] = $xml->xpath('/results/facets');

  return $results;
}

function delvingsearch_facets() {

  if (delving_has_searched() == TRUE) {
    $facets = array();
    // Use the response cache to grab the facets
    $xml = delving_static_response_cache();
    // Check to make sure we have an XML object to work with
    if (!is_object($xml)) {
      $xml = new SimpleXMLElement($xml);
    }
    // Are there any results?
    if ($xml->query['numFound'] > 0) {
      // Use xpath to create facets as array
      $facets['facets'] = $xml->xpath('/results/facets/facet');
      $facets['query'] = $xml->xpath('/results/query/terms');
    }
  }
  else {
    $facets = 0;
  }
  return $facets;

}


function delving_remove_element($arr, $val) {
  foreach ($arr as $key => $value) {
    if ($arr[$key] == $val) {
      unset($arr[$key]);
    }
  }
  return $arr = array_values($arr);
}

function delvingsearch_breadcrumbs() {
    if (delving_has_searched() == TRUE) {
        $xml = delving_static_response_cache();
        $breadcrumbs = array();
        // Check to make sure we have an XML object to work with
        if (!is_object($xml)) {
            $xml = new SimpleXMLElement($xml);
        }
        if ($xml->query['numFound'] > 0) {
            $breadcrumbs = $xml->xpath('/results/query/breadCrumbs/breadcrumb');
            //           drupal_set_message(print_r($breadcrumbs));
        }
        $out = '<div class="delving-breadcrumbs">';
        $out .= 'Your searched for: ';

        // Temporary measure until HASDIGITALOBJECT is a hidden query filter
        //$crumbs = delving_remove_element($breadcrumbs, 'HASDIGITALOBJECT:true');

        $numItems = count($breadcrumbs);
        $i = 1;
        foreach ($breadcrumbs as $crumb) {

            $text = $crumb;
            $href = url(variable_get('delving_search_page_path', DELVING_SEARCH_PAGE_PATH)) . '?query=' . str_replace('query=', '', $crumb['href']);

            if ($i != $numItems) {
                $out .= '<a class="crumb" href="' . $href . '">' . $crumb . '</a>&#160;>&#160;';
            }
            else {
                $out .= $crumb;
            }

            $i++;

        }

        $out .= '</div>';
        return $out;
    }
}



