<?php
// $Id:
/**
 * @file
 * Uninstall variables used by the Delving-Remote-Search Search module.
 */

/**
 * Implementation of hook_uninstall().
 */
function delvingsearch_uninstall() {
  variable_del('delving_search_page_name');
  variable_del('delving_search_page_return');
  variable_del('delving_search_results_page_path');
  variable_del('delving_search_item_page_path');
  variable_del('delving_search_item_view_path');
  variable_del('delving_search_item_external_url');
}
